### ISSUE TITLE
KeyError: 'default_destination'

### ISSUE THREAD

**Issue by durzo** [tsileo/bakthat#18]
after installing bakthat and running configure i get the following on some commands (ls)

$ bakthat ls
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.4.5', 'console_scripts', 'bakthat')()
  File "/usr/local/lib/python2.7/dist-packages/bakthat/**init**.py", line 690, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/aaargh.py", line 157, in run
    return func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bakthat/**init**.py", line 580, in ls
    storage_backend = _get_store_backend(conf, destination, profile)
  File "/usr/local/lib/python2.7/dist-packages/bakthat/__init__.py", line 44, in _get_store_backend
    return STORAGE_BACKEND[destination](conf, profile)
KeyError: 'default_destination'

the contents of my ~/.bakthat.yml are:

default:
  access_key: [removed]
  default_destination: glacier
  glacier_vault: test
  region_name: ap-northeast-1
  s3_bucket: test
  secret_key: [removed]

note: backing up seems to work OK

**Comment by tsileo** [comment]
Hi,

First, thanks for your feedback !!

I haven't finished to update the docs yet,my bad, you shouldn't be using <code>bakthat ls</code>, but instead you should be using <code>bakthat show</code>, which is basically the same thing, but the <code>show</code> subcommand is more powerful.

Let me know if you have still a bug with <code>bakthat show</code>

Also there is a known bug (which will be fixed in the next few days) with the default destination, so you have any issue, put the <code>-d</code> argument in the command.

Also don't hesitate if you have any question, suggestion, issue or idea !!
