### ISSUE TITLE
Not possible to specify custom conf file

### ISSUE THREAD

**Issue by pavel-paulau** [tsileo/bakthat#20]
According to

https://github.com/tsileo/bakthat/blob/master/bakthat/conf.py#L8

path to conf file is hard coded. Was it design decision?

**Comment by tsileo** [comment]
Yes the path to the config file is hard coded, because I think dotfiles are good for storing config files, but you're right, sometimes it can be useful to be able to use another config file.

I think I will add a <code>-c/--config</code> option to every commands, or do you have a better suggestions ?

**Comment by pavel-paulau** [comment]
Sounds good!

**Comment by stephantual** [comment]
Brilliant, thank you

**Comment by tsileo** [comment]
The new -c/--config argument is available in bakthat 0.5.1. Let me know if you have any feedback/issues !

**Comment by pavel-paulau** [comment]
Cool! Many thanks @tsileo !

**Comment by tsileo** [comment]
There was an issue with bakthat 0.5.2, I just released bakthat 0.5.3, now it should works, keep me updated !

**Comment by pavel-paulau** [comment]
Just upgraded my code. Everything works as expected. Awesome!

**Comment by tsileo** [comment]
Thanks! Let me know if you have another idea/suggestion.

Also, I would love to hear your feedback about [BakManager](https://bakmanager.io) ([Bakthat and BakManager integration](http://docs.bakthat.io/en/latest/bakmanager_integration.html)) !
